### ISSUE TITLE
partition redundancy for bugged supports 

### ISSUE THREAD

**Issue by vecna** [dyne/Tomb#137]
Hi ! I've a damaged SD cards, that is losing something bytes.

I want using Torm over it, Using two partition, I can do an LVM between and make a mirror raid.
This will minimize the corrupted cluster. just, I don't know which is the stablest way :(

It is better make mirroring of the encryption partition, or inside the encrypted partition ? 
can be implemented in Tomb the creation of a "twin tomb" ? like a cemetery chapel, if you want a metaphor :) ?

**Comment by jaromil** [comment]
Just a heads up here, running a few tombs into a ZFS graveyard since a while now and all seems to be fine and quiet. No walking dead around, all flowers in the pots.

**Comment by jaromil** [comment]
I am experimenting with btrf and snapshot support inside tombs. Seems like a better approach to redundancy to me. else using zfs on sdcard externally to tomb is still a good option.

**Comment by hellekin** [comment]
Something I like a lot about Tomb is the lack of choice: the defaults are usually good enough and keeping the system simple is always a great advantage.  If you're looking into alternate solutions, I'd suggest finding a stable one and sticking to it.  BTRFS sounds interesting because of the snapshots and volumes.  Maybe that could help implement nested hidden tombs (or not, just thinking aloud).  Another thing to take into account is the specificity of the support: HDD, SSD, and RAND Flash memory don't work the same, and we probably don't want to get too much in gory details.  I would opt for anything will remain conservative wrt disk lifetime.  Generally I'd like to work on stripping stuff from Tomb rather than adding to it.

**Comment by jaromil** [comment]
I guess this can be closed. Mirroring is up to other applications, while creating tombs inside ZFS or btrfs helps prevent bitrot.
