### ISSUE TITLE
specifying kdf key hash

### ISSUE THREAD

**Issue by deathtrip** [dyne/Tomb#216]
Currently there's no way to choose the hash used by PBKDF2.
Adding an -h option for the lock operation, to select the hash, would be good.

When i read the manpage, which says tomb uses by default aes-xts-plain64:sha256. I thought sha256 is used as the hash, as plain mode doesn't need a hash function for the initialization vector like essiv does.

**Comment by hellekin** [comment]
What is the use case for choosing a different hash @deathtrip?

In any case, `-h` is already used for help, so it would be another key.  Still, I don't know why we should vary the hash in that case.

**Comment by deathtrip** [comment]
There's the -o option of choosing the algorithm and operation mode, so it only makes sense to allow to choose the hash also. And most importantly SHA1 is not a secure function, and we have better alternatives available. Encryption software is generally moving away from it, if it has not already.

**Comment by hellekin** [comment]
Yes, then we should probably use a better hash and move on.  Having a
choice there sounds like, hmmm, quite useless.  Tomb should use the best
available solutions, and keep being compatible with older Tombs, even if
that means "upgrading" the existing tombs.

my .02c

**Comment by deathtrip** [comment]
Choice is never useless, especially in open source software. And what are exactly the "best" solutions?  
We can never know which function/algorithm will be broken first.

**Comment by jaromil** [comment]
I am in favor of strong defaults and freedom of choice.

Are you talking about exposing the --cipher option in cryptsetup luksCreate?

if yes, that is already exposed via the -o option when using the `tomb lock` command.
It is also stated in the manpage.

**Comment by jaromil** [comment]
I got confused: you suggest to be able to change the hash for the extras pbkdf2 program.
I think is a good idea! will look into it

**Comment by boyska** [comment]
On Tue, Sep 15, 2015 at 12:57:10AM -0700, Jaromil wrote:
>I got confused: you suggest to be able to change the hash for the
>extras pbkdf2 program.
>I think is a good idea!

why is it? (ie: which advantage could this feature give?)

**Comment by jaromil** [comment]
I need to look into this still, but the advantage would eventually be progress and choice.
the -o option is still unused for the forge operation.

**Comment by boyska** [comment]
> the advantage would eventually be progress

what do you mean?

> and choice

choice on its own is not a feature when it's completely unclear why someone should choose something else than the default.

Anyway, this is the relevant line:
https://github.com/dyne/Tomb/blob/master/extras/kdf-keys/pbkdf2.c#L127
Changing the hash using some option is rather easy, and that's one of the reasons why I consider this proposal an example of featurism.

**Comment by hellekin** [comment]
"progress and choice" do not sound neither technical nor convincing.
What is the price and scope of this?

Who is going to use this option?

I'd rather have "best" solutions (i.e. "strong defaults") than choice.
We already made the choice to only use one slot, and lock the encryption
algorithm.  I don't see anything interesting for Tomb coming from
enabling choice of the PBKDF2 hash. "Progress and choice" will not
convince me because 1) when I hear progress, I think about regress
(there's always two sides to a coin); 2) choice is not necessarily
useful; in any case it should be optional.

Maybe we could instead think about an _expert mode_, where people who
know what they're doing can enable kilometer long command line options
and have it to their taste.  But for normal operation, please let's not
clutter the command line options, as we don't have too many, and _too
much choice_ only brings confusion.  If we open this option, then why
not have the option to use a different encryption algorithm, and why not
enable the option to use more than one slot?

==
hk

**Comment by deathtrip** [comment]
Strong defaults and choice are not mutually exclusive. If a setting is optional, it doesn't clutter the command line. And we already have an option to use a different encryption algorithm.

**Comment by boyska** [comment]
> Strong defaults and choice are not mutually exclusive.
>
unnecessary choice on security related software is a source of bugs. Or
maybe a bug on its own
>
>   And we already have an option to use a different encryption algorithm.
>
That has at least an explanation: older cryptsetup version only support
certain modes, so having a way for a user to specify that she wants
retro compatibility is useful.

There is nothing similar about pbkdf-sha1.

**Comment by hellekin** [comment]
> If a setting is optional, it doesn't clutter the command line.

This is not what I meant.  We're using short options for commands, and
these are global, so basically we're limited to 26 letters, 10 digits
and a few special characters.  Grabbing one of those for this kind of
option does not seem like a good idea to me.

That said, we'd certainly benefit from using a better algo than SHA1.

**Comment by boyska** [comment]
> That said, we'd certainly benefit from using a better algo than SHA1.
why? If I'm not wrong, preimage resistance is all that's needed for
pbkdf2 to be secure.

**Comment by hellekin** [comment]
> why? If I'm not wrong, preimage resistance is all that's needed for
> pbkdf2 to be secure.
>

right.  Then are we talking about a non-issue?

**Comment by jaromil** [comment]
I still agree with @deathtrip: if `-o` is optional for `forge` the only problem to leave it open is to add another case to the rendering of the text header in KDF enabled tomb keys, see https://github.com/dyne/Tomb/blob/master/tomb#L963

I did obviously predicted some progress there by inserting a case switch with the only option being `pbkdf2sha1`.

Said that, @boyska is right there is no real improvement in using a stronger hash for a KDF algo, AFAIK.

**Comment by jaromil** [comment]
@deathrtip wrote:
> When i read the manpage, which says tomb uses by default aes-xts-plain64:sha256. I thought sha256 is used as the hash, as plain mode doesn't need a hash function for the initialization vector like essiv does.

Yes, you are right about the initialization vector for xts-plain64 not needing a hash function, but you are confusing what that :sha256 stands for :shipit: 

First of all, the reason why the default is stated with the `aes-xts-plain64:sha256` string is that cryptsetup accepts that as a valid switch. After all, we are just a wrapper and prefer to add as less sophistication as possible on top of settings. What the `-o` switch does right now for the `lock` command is passing that string as-is to `cryptsetup luksFormat`'s option `--cipher` (see cryptsetup manpage).

From cryptsetup's POV the `:sha256` is in place to indicate that the *passphrase* is hashed with SHA256. LuksDump further indicates the hash used for the header, which is SHA1 by default for Luks volumes and cannot be changed using cryptsetup by commandline AFAIK. Example of luksDump:
```
Cipher name:   	aes
Cipher mode:   	xts-plain64:sha256
Hash spec:     	sha1
```

Back to the KDF debate, I'd like to know what other hashing algos are implemented by libgcrypt at the moment for replacing the `GCRY_MD_SHA1` in our code. I don't think it is a priority for our security to change that ASAP, but certainly when we will change it we'll need a switch at least in order to preserve backward compatibility.

**Comment by jaromil** [comment]
I label this issue minor because if there is any work to be invested in strengthening KDF keys in Tomb, we already agree that should go in the direction indicated by issue #214.

**Comment by deathtrip** [comment]
@jaromil wrote:
> First of all, the reason why the default is stated with the aes-xts-plain64:sha256 string is that cryptsetup accepts that as a valid switch. After all, we are just a wrapper and prefer to add as less sophistication as possible on top of settings. What the -o switch does right now for the lock command is passing that string as-is to cryptsetup luksFormat's option --cipher (see cryptsetup manpage).
> 
> From cryptsetup's POV the :sha256 is in place to indicate that the passphrase is hashed with SHA256. LuksDump further indicates the hash used for the header, which is SHA1 by default for Luks volumes and cannot be changed using cryptsetup by commandline AFAIK.

The "Hash spec" from luksDump can be changed with the cryptsetup --hash option at volume creation, as i have on my drive right now, and is what i proposed to change.
The cryptsetup manpage states about the --hash option:
"For create action specifies hash to use for password hashing.
For luksFormat action specifies hash used in LUKS key setup scheme and volume key digest."

While not saying anything about any hash under the --cipher option.
Now i'm confused, as i thought the sha256 after the cipher was unneeded, cause it could be specified by the cryptsetup --hash option.

**Comment by jaromil** [comment]
Some time passed. Do we have any further understanding of cryptsetup behaviour on this issue?

**Comment by nerun** [comment]
It's 2024, version 2.10, option `-o` exists and we can choose all these ciphers:

IDEA 3DES CAST5 BLOWFISH AES AES192 AES256 TWOFISH CAMELLIA128 CAMELLIA192 CAMELLIA256

Close issue?
