### ISSUE TITLE
possible better key stego [feature request]

### ISSUE THREAD

**Issue by fullmetal1** [dyne/Tomb#225]
right now I'm using a bash script that does

`tomb exhume ${keyfile//[\"\']/} | tomb open ${tombfile//[\"\']/} -k cleartext --unsafe -f`

the key plaintext is steghidden with aes encryption beforehand, and then exhumed and piped from stdio to tomb open.

I suspect that this would be a much better way to do stego than exhuming the pgp encrypted keyfile, and then using that to open the tomb.

It avoids the extra step of getting the file from the image, and leaves no trace (except for in terminal history)

**Comment by jaromil** [comment]
Have you noticed that since a couple releases you can use directly the image as argument of the `-k` option? it is all handled internally with a call to `exhume_key`, see https://github.com/dyne/Tomb/blob/master/tomb#L986

do you see any problems with that?

**Comment by fullmetal1** [comment]
It seems fine except for not really being documented in the manpage (or maybe I just missed it).

Since the purpose of steghiding the key is to hide where the key is, I think that terminal history makes it a little pointless for daily use.

I have it set up so that I enter the key file into my script so that it never gets saved to bash history (and thus I don't have to shred my bash history every time). Would there be a way that if you don't enter your keyfile when calling tomb it prompts you to do it?

Just a suggestion though.

**Comment by arthaud** [comment]
If you use zsh, just add `alias tomb=' tomb'` in your .zshrc
When a command starts with a space, zsh doesn't put it in the history (that probably works with some other shells).

This tip should probably be written somewhere.

**Comment by jaromil** [comment]
Yes, is documented here https://github.com/dyne/Tomb/blob/master/INSTALL.md#deleting-history

Even if they are not ending up being bugs, thanks @fullmetal1 for poking around and letting us know.

I'll give an edit to the manual page to also include these things, it needs it. On another front @parazyd noticed the `sudoers` method described in manpage to allow users to use tomb on a system doesn't work since the latest refactoring of privilege escalation.
