### ISSUE TITLE
Tomb mount without sudo password

### ISSUE THREAD

**Issue by gion86** [dyne/Tomb#228]
Hello, 
I tried to configure my system as of tomb manual, with the line:

`username ALL=NOPASSWD: /usr/bin/tomb`

But still when I run

`# tomb open /tomb_file /mnt/tomb -f -k key.idx -q`

it ask for a sudo password. Is it normal? Maybe it's not a bug but it my distro not correctly configured... (Archlinux)

I've noticed that /usr/bin/losetup is the one requiring a password here, but adding this to sudoers files:

`username ALL=NOPASSWD: /usr/bin/tomb, /usr/bin/losetup`

would be a big security hole, am I right??

So what should I do? 

Thankyou!

**Comment by jaromil** [comment]
This is on my mind since a while now: a change in the way tomb handles sudo, which considerably simplified the code, broke the behavior documented in the manual.
It is not due to your distro, but to the fact now sudo is called on each internal command.
It would be also a security threat to add each single command to sudoers NOPASSWD considering among them are `chown` and `chmod`.

I'm currently considering to avoice the `ch[own/mod]` made on tombs when mounted and then add a list of commands to add to sudoers. losetup is somehow safe, as others.

There will be another approach documented, that is implying the use of `sup` in place of `sudo`, see https://sup.dyne.org

**Comment by aude** [comment]
I am also interested in resolving this bug.

This is a duplicate of the bug #223, which actually investigates the issue and explains the cause. The offending line is https://github.com/dyne/Tomb/blob/c502ef3d921c10f8bfc9ccff70c041575a4f5f66/tomb#L215. It overrides `$USERNAME`, and that seems to make `sudo` think that the caller is whatever `$USERNAME` says.

Is it necessary to set `$USERNAME` in `_whoami`?

**Comment by jaromil** [comment]
I'm running tests and you seem to be right: by commenting line 215 in tomb the tomb script inclusion in sudoers works (and all tests are passed). Have you tried it also? any collateral effects spotted?

**Comment by aude** [comment]
Yes, I've done it as well for the time being. Haven't had any casualties so far.

As far as I can see, `$USERNAME` is not used by the tomb script itself.
