### ISSUE TITLE
Proposed change for when encrypted swap is found

### ISSUE THREAD

**Issue by mandeep** [dyne/Tomb#229]
Currently when tomb finds an encrypted swap partition, the following message is sent to stdout:
```
"All your swaps are belong to crypt. Good."
```

I propose changing this to something more informative along the lines of:
```
Encrypted swap partition found. Swap partition is safe.
```

Thoughts?

**Comment by hellekin** [comment]
> Thoughts?
> 

Doesn't it lack personality?

**Comment by mandeep** [comment]
> Doesn't it lack personality?

I agree it's a bit dry, do you have a statement in mind that is both whimsical and informative?

Maybe something like
```
Encrypted swap partition found. Your swap is safe from the undertaker.
```
or
```
The undertaker found an encrypted swap partition. Good.
```

**Comment by jaromil** [comment]
Perhaps the second. Hassling to have to change all translations.. actually I'm curious how this joke has been translated...

**Comment by mandeep** [comment]
Can the original message even be translated to other languages? Seems like something that only exists in English.

**Comment by jaromil** [comment]
Its all in `extras/translations`

The italian one kept literal: "Tutti i tuoi swap appartengono a crypt. Bene."
which indeed doesn't sounds informative nor as funny as in English.

**Comment by hellekin** [comment]
Most jokes or poems are not translatable.  Colloquial expressions that
are not translatable literally are usually translated to another,
similar expression that conveys the same meaning in the culture
associated with that language.

"[All your base are belong to
us](https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us)" has a
specific history and context that conveys a certain humor and
**culture** but it would be a shame to abandon it for that reason.  If
you really want to "do it", why not take the translations used by
others, like in Wikipedia, that translate, e.g., [in
French](https://fr.wikipedia.org/wiki/All_your_base_are_belong_to_us):

> Toutes votre base sont appartiennent à nous.

Or [in
Italian](https://it.wikipedia.org/wiki/All_your_base_are_belong_to_us):

> Tutte le vostre base sono appartengono a noi.

I would vote to use **these** instead of the more classical,
_informative_, **utilitarian** versions that we have now, that hardly
convey any personality.  If people have issues understanding what that
means, at least they will learn something, and enjoy some **human**
experience.

**Comment by mandeep** [comment]
@hellekin As you said, translating the English phrase would lose its meaning even if it's translated into a similar expression. Also, making people search for the meaning behind a message in an application would be considered inhumane to most ;). Considering how old and overused the original phrase is, I think it makes most sense to abandon it. Most new users my age and below were born after the origin of the phrase and after it had even become a meme.

**Comment by jaromil** [comment]
ok well now i'm really feeling old lol

**Comment by gdrooid** [comment]
I agree with @mandeep.

**Comment by jaromil** [comment]
Overall, I also agree with @mandeep. I doubt any small change like this can erase the character that Tomb already has (for instance, by being called tomb).
