### ISSUE TITLE
Remove --shared in favor of -r

### ISSUE THREAD

**Issue by jaromil** [dyne/Tomb#252]
Is there anything preventing us to remove the --shared flag in favor of a multiple entry detection on the -r flag when in gpg -g mode?
I am wondering since that will simplify the usage of gpg asymmetric keys overall.

**Comment by roddhjav** [comment]
The `--shared` flag is not a technical requirement (tomb does not need this flag to detect the presence of more than one recipient). I implemented this flag only as a ACK from the users they are going to encrypt the tomb key with more than one gpg key. If you think it is not needed, we can get rid of this flag.

We can have a multiple entry detection on the `-r` option instead of separating the key id by a coma in the same -r entry. However, I don't know if tomb support multiple option entry. That said, (in my opinion) it would be a better solution.

**Comment by jaromil** [comment]
I really think is better to remove `--shared` and have comma separated multiple options on `-r`. If something would require conscious confirmation then the `--force` flag is there for that, but I believe this is not a case requiring it.

For parsing comma separated strings there is the `strtok()` function provided by zuper which is available inside Tomb.

**Comment by jaromil** [comment]
thanks, feel free to open a PR when ready with this, or I can merge it by hand from your branch.

**Comment by roddhjav** [comment]
The PR is not ready yet, I'm investigating a few bugs regarding GPG options, I will submit a PR when all this work will be ready.
