### ISSUE TITLE
Keyfile size maybe too small?

### ISSUE THREAD

**Issue by ghost** [dyne/Tomb#276]
Hi!
You seem to forge a 512 byte Key. It seems to me that you wanted to forge a key which size corresponds to the cipher key size (which is 512bit) and mixed bits and bytes :). However, as you are not working in PLAIN mode (that would cut the keyfile to the corresponding cipher key length) but rather in LUKS mode, this keyfile is just an input for PBKFD2. Here you want to maximize the entropy and I am not sure (I am by far no crypto expert), but I guess a keyfile size of some kilobytes would be much more secure for like zero costs. Maybe everything is fine, but what was the design decision for the 512 byte? If you want to match with the cipher key size, why didn't you choose 64 byte?

**Comment by jaromil** [comment]
See issue #226

**Comment by jaromil** [comment]
You are right, we mixed bits and bytes :^P
Fixing this will come handy as we need to save space in the key to fit more features in some future.

**Comment by danvari** [comment]
What do you mean by "PBKDF2 is optional"? I thought as long as you use "--key-file" in LUKS mode you always make use of PBKDF2. The keyfile in LUKS mode is just the passphrase for PBKDF2. But in PLAIN mode "--key-file" is equivalent to the cipher key.

So in LUKS mode you now depend on the statistics of the PBKDF2 mapping, which is why you want to increase the input (keyfile) to maximize the entropy. Maybe everything is fine, but I see people out there using keyfiles of some KB length, upto some MegaBytes. On the other side I would say a 512 Byte passphrase (~ 512 characters) is super secure.

I just want to raise a discussion about this, as I said, I am not sure whether this is sufficient or not :).

**Comment by jaromil** [comment]
There are different layers of PBKDF2 in Tomb. One is embedded in GPG, one is our own in `extras` and one I didn't knew of you mention is in LUKS. I see in the docs that 512 BITS are enough so this is a valid observation, in any case better exceed than anything else (better safe than sorry). This conclusion also invalidates the change you suggested and we operated in #238 since the AES-256 was already kicking in with 256BYTES keys.

**Comment by boyska** [comment]
Jaromil:
>There are different layers of PBKDF2 in Tomb. One is embedded in GPG

I don't think that GPG embeds PBKDF2.
I think that GPG has some form of KDF, though

>one is our own in `extras` and one I didn't knew of you mention is in LUKS

IIRC, LUKS does pbkdf2 only for passphrases, not for keyfiles

>I see in the docs that 512 BITS are enough

On man 8 cryptsetup I see that when a keyfile is used "It will be truncated to the key size of the used cipher or the size given by
       -s and directly used as binary key"

So bigger keyfiles do not help.

**Comment by danvari** [comment]
> IIRC, LUKS does pbkdf2 only for passphrases, not for keyfiles
Do you have any source for this? Have a look at the man page in section "NOTES ON PASSPHRASE PROCESSING FOR LUKS". There you can read:

> LUKS uses PBKDF2 to protect against dictionary attacks and to give some
> protection to low-entropy passphrases (see RFC 2898 and the  cryptsetup
> FAQ).

and

> From key file: The complete keyfile is read up to the compiled-in maxi‐
> mum  size.  Newline  characters  do not terminate the input. The --key‐
> file-size option can be used to limit what is read.

I guess the maximum size is 8192KB if I remember correclty.

**Comment by boyska** [comment]
Stephan Schindel:
>> IIRC, LUKS does pbkdf2 only for passphrases, not for keyfiles
>Do you have any source for this? Have a look at the man page in section "NOTES ON PASSPHRASE PROCESSING FOR LUKS". There you can read:

You're right, I misread the manpage.
Double-checked reading source code which confirms that PBKDF2 is applied
both to passphrases and keyfiles (but obviously not to
--master-key-file)

>> From key file: The complete keyfile is read up to the compiled-in maxi‐
>> mum  size.  Newline  characters  do not terminate the input. The --key‐
>> file-size option can be used to limit what is read.
>
>I guess the maximum size is 8192KB if I remember correclty.

keep in mind, however, that the symmetrical encryption key is smaller
than this. So an attacker will just attack that, without bothering with
bruteforcing such a huge keyfile.
