### ISSUE TITLE
'dcfldd:: No such file or directory' + Error creating the extra resize ::1 size::, operation aborted.

### ISSUE THREAD

**Issue by tombraidr** [dyne/Tomb#280]
I was resizing a 10GB tomb to 20GB, and everything looked fine then my computer crashed.  So I rebooted and tried again but got this:

```
$ tomb resize -s 20000 /media/something/secret.tomb -k secret.tomb.key
tomb  .  Commanded to resize tomb /media/something/secret.tomb to 20000 mebibytes.
tomb  .  Valid tomb file found: /media/something/secret.tomb
tomb  .  Key is an image, it might be valid.
tomb  .  Generating secret.tomb of 20000MiB
dcfldd:: No such file or directory
tomb [E] Error creating the extra resize ::1 size::, operation aborted.
```

Tomb seems ok because I can still open it. Also, the filesystem where the tomb is mounted is fuseblk. 

Any ideas, suggestions on what happened/what to do? Thanks!

**Comment by jaromil** [comment]
Hi! do you have any new clues about this? I couldn't find any related problem in the code.
`dcfldd` is an optional dependency used instead of `dd` to show a progress bar on `dig` operations. It is detected using `command -v dcfldd` at start and its path saved into $DD which is then used to run it. The strange thing in your case is that it has been detected in the path but then its not found when launched.

About the resize, good some time ago I've fixed it to be able to restart where it was left in case of damage. Been in a similiar situation myself ;^P
