### ISSUE TITLE
auth.log contains sudo use detailing bury, exhume with all commands issued

### ISSUE THREAD

**Issue by oldhoghead** [dyne/Tomb#302]
I am not an expert, but have been using tomb to keep some information private, I discovered looking at my auth.log that any usage of sudo + tomb was duly recorded there, whereas if I only used root via su to execute tomb arguements, there were no details to be found. 

Thank You,

ohh

**Comment by stevesbrain** [comment]
This is pretty normal for sudo. You can disable it on a per-command basis:

```
Cmnd_Alias TOMB = /usr/sbin/tomb
Defaults!TOMB !syslog
```

**Comment by oldhoghead** [comment]
Thank you, figured there was a solution, I'm just an old man trying to keep up.

cheers
ohh

**Comment by jaromil** [comment]
A slightly OT reflection, thanks to this issue for inspiring it:
The main reason why Tomb uses sudo is to enable per-user tomb execution and to know the user opening the tomb so that a chown can be ran when open. But I now come to think that by having an "ownership_hook" inside the tomb one could configure this behavior also when opening from su. The reason I think about this is that many people out there do not like sudo and it would be nice to not force them into that.

**Comment by oldhoghead** [comment]
Thank your team for an awesome program, thank you for the follow up, the reason I had used sudo was the suggestion on https://www.dyne.org/software/tomb/  "Please note that user permission problems are due to the fact they are not using sudo. We do recommend using it."

Only later perusing through my /var/log files  I noticed the full disclosure of all of my efforts were detailed. It makes sense as you say for determining who's been accessing. OTH  I was trying to not leave a trail.
cheers,ohh

''' 

    On Tuesday, January 23, 2018 2:32 AM, Jaromil <notifications@github.com> wrote:
 

 A slightly OT reflection, thanks to this issue for inspiring it:
The main reason why Tomb uses sudo is to enable per-user tomb execution and to know the user opening the tomb so that a chown can be ran when open. But I now come to think that by having an "ownership_hook" inside the tomb one could configure this behavior also when opening from su. The reason I think about this is that many people out there do not like sudo and it would be nice to not force them into that.—
