### ISSUE TITLE
Would it be possible to make zsh dependency at least, optional?

### ISSUE THREAD

**Issue by q2dg** [dyne/tomb#547]
I'm a regular mainstream linux distros user and I'm fine just with bash. I don't know the technical details, but installing another shell seems a little weird at first sight. 
Thanks!

**Comment by Narrat** [comment]
Oh, it isn't that weird if you think of shells as "programming interfaces" or environments. ;) And scripts run in their specific environment, like with `python` and `perl` scripts. Perl cannot replace the python interpreter to execute python scripts.
And all the shells have their differences. Some are more subtle than others. But if for example a shell script is explicitly written in and for `csh` you cannot run it with `bash` or `dash`.
The differences in shells may not be that obvious as there is the POSIX shell (shebang `!# /bin/sh`), which is the reason why shell scripts can be cross-platform (or rather cross-shell). A common denominator between shells and it is standardized.
And easy source for subtle bugs. Scripts claim to be POSIX `sh`, but on any system without the `bash` it may explode because of "bashismns" in use.
What are some of those differences?
* test: `[[ condition ]]` is not availabe in `sh` (it's `[ condition ]` with less features)
* Arrays do not exist in `sh`
  * instead IFS (internal field separator) is being used as a "replacement" mechanic
* `local` as a keyword for variables does not exist in `sh`
  * subshells need to be used instead 

And with that rather long and incomplete introduction back to your question: The script used to use `ZSH` specifics, which weren't available with `bash`, `dash`, `csh` or `ksh`. Therefore it is explicitly a `zsh`-script (shebang: `#! /usr/bin/env zsh`) and in a sense not cross-plattform or cross-shell. I'm being rather vague on that, as I'm not that firm with differences between `zsh` and `bash`. @jaromil could answer this better than me.
That being said I don't know if it would be possible to get it easily ported to another shell. If it is rather similar to `zsh` (like `bash`) the answer is probably yes. But it would be a lot of hassle to get it `POSIX` compliant. In general a switch will likely be out of scope.
And think about it the other way around. All those people, which don't use `bash` as the default shell (Debian has `dash`, others use `zsh`, `fish` etc) still need to have the `bash` installed because of `bash`-scripts :D ;)

**Comment by q2dg** [comment]
Oh, thanks a lot for your so clear explanation.
If you don't mind, then, I'll close this issue
Thanks!
