### ISSUE TITLE
deniable encryption (decoy inner tomb)

### ISSUE THREAD

**Issue by boyska** [dyne/tomb#81]
Wait: we'll explain what we mean with this.
Sometimes we MUST reveal the password, and the enemy has the keyfile. We've lost.

BUT what if we had two filesystem, one "clean" and the other really secret, with two different passwords? we could reveal the wrong one, asserting that is what we were hiding.

how to do this?

ideas:
1. steganographic filesystem on top of the ext3 inside the tomb. urgh, that sounds hard. and steganography sucks
2. using the free space of the disk https://en.wikipedia.org/wiki/Deniable_encryption#Modern_forms_of_deniable_encryption this is not perfect, as this is subject to statistical methods to prove that there is indeed some data, not just free space.

**Comment by hakavlad** [comment]
@JoelMon 

>No hidden volumes = Give password, volumes open, people see you only have tax return documents and other innocent documents. Little incentive for keeping you around.

You cannot prove that you are not hiding encrypted files somewhere else. You cannot prove that you have not volumes at all (hidden ot not).

>you can not convince anyone that you do not have a hidden volume

This is true even if the attacker did not find a single encrypted file at all. Even if encrypted files not found on your disk, there is still a chance that you are hiding something somewhere. So, following your logic, the attacker has a reason to torture you anyway, even if you only use 7z or PGP.

Just because I didn't find any disks on you during my search doesn't mean you're not hiding them somewhere else. The absence of hidden information cannot be proven in any case.

Thus, on the one hand, the use of hidden volumes can be useful in legal states where torture is prohibited and evidence is needed to imprison. On the other hand, refusing to use hidden volumes will not save you from torture where the law and humanism are not respected: you cannot prove that you are not hiding something, and you can be tortured even if no storage media was found on you at all.

**Comment by hakavlad** [comment]
@StrangeTcy 

>No amount of encryption will save you from such people

Yes. It is impossible to prove that you are not hiding files somewhere. There is no way to prove that you are not using some kind of steganography technique. However, steganography will help where the attacker needs evidence to coerce you.

**Comment by hakavlad** [comment]
@jaromil 

>Ultimately if one desires to be able to give up all secrets to avoid things like torture then should be using an encryption scheme permitting that

There are no such encryption schemes. You cannot prove that you are not hiding data anywhere. You cannot prove to the attacker that he found all your disks during a search.

**Comment by hakavlad** [comment]
Everyone knows that photos of cute animals can contain hidden information. How do you prove to an attacker that you are not hiding anything in your photos?

Thus, hidden containers are no more dangerous than photos of cats and dogs.
